### ISSUE TITLE
demos dont work in chrome

### ISSUE THREAD

**Issue by rensi4rn** [SwarmOnline/Ext.ux.TouchCalendar#37]
demos dont work in  new chrome 43

**Comment by andrewmduncan** [comment]
I can't replicate. I am using Version 43.0.2357.81 (64-bit).

**Comment by rensi4rn** [comment]
I have the same version chrome  43.0.2357.81,
yo veo 
http://www.swarmonline.com/Ext.ux.TouchCalendar/examples/Ext.ux.TouchCalendarEvents-2.html

![image](https://cloud.githubusercontent.com/assets/2071383/8035188/5f65a30a-0dbc-11e5-93e1-f89364ca4b95.png)

in opera i see

![image](https://cloud.githubusercontent.com/assets/2071383/8035172/41b66e02-0dbc-11e5-8eea-ffd0b53c8991.png)


the problem and solution are described here ....

http://www.ladysign-apps.com/developer/chrome-43-breaks-sencha-touch-modern-toolkit-and-how-to-fix-it/#.VXWQbc9_Oko
